### ISSUE TITLE
Support excluding files from black formatting

### ISSUE THREAD

**Issue by pmeier** [omnilib/ufmt#12]
While `usort` is relatively harmless, formatting files with `black` can introduce a lot of vertical space that is not always wanted. Especially in the documentation such as usage examples, directives to disable it locally (`# fmt: off` / `# fmt: on`) are undesirable. 

`black` has an `--exclude` option that can also be given through its configuration in the config file. Maybe we can add a flag to `ufmt_string` that disables `black` formatting. With #11 merged, this flag could be set in `ufmt_file` after parsing the black configuration file.

**Comment by pmeier** [comment]
I gave it a short try and hit a roadblock. My initial plan to let `ufmt_file` determine if a file should be skipped or not does not work, because the the `black` exclude pattern is defined relative to a root directory, but `ufmt_file` has no notion of that. Thus, this would actually need to happen in `ufmt_paths`.

**Comment by jreese** [comment]
@pmeier I'm not personally fond of the idea of trying micromanage which files get formatting vs sorting vs both. I'd rather have a single config option to exclude extra paths beyond what's in the project's `.gitignore`, and just not skip any formatting or sorting altogether on the excluded files.

I have a simple PR in omnilib/trailrunner#1 to add an `excludes` parameter when walking directories. This would allow µfmt to have a new option in `pyproject.toml` to exclude one or more paths, and disable formatting on those excluded paths.

Would that be sufficient for your use case?

**Comment by pmeier** [comment]
Yes, I think that would be sufficient (checking with @NicolasHug). This would mean we cannot invoke `usort` or `black` directly, because they would not pick up on any configuration, but I don't think this is an issue.

On that note, is there a reason to put the configuration in `pyproject.toml` and not for example in `ufmt.ini`? Just having a `pyproject.toml` in a repository changes the build behavior which can have [unintended side effects](https://github.com/psf/black/issues/683#issuecomment-487306157).

**Comment by jreese** [comment]
Having multiple sources of configuration makes everything more complicated. It invokes questions of precedence/priority and conflicting vs supplemental options, let alone dealing with different formats for each file. Both black and µsort only look for their configurations in pyproject.toml, so having a separate location for configuration also opens the door to needing either duplicated configuration options for black/usort in this special file, and the possibility of getting different behavior if running usort or black on their own.

Beyond that, pyproject.toml is the only well-defined location for project configuration, and proliferation of bespoke configuration files for each tool is not something I want to encourage. pip's support has greatly improved since 2019, and most of the concerns listed were already addressed back then. By this point, I'm not aware of any setuptools-incompatible behaviors in pip that would prevent a project from having a pyproject.toml.

**Comment by NicolasHug** [comment]
> Yes, I think that would be sufficient (checking with @NicolasHug).

I agree

**Comment by pmeier** [comment]
@jreese if you want I can send a PR here, as soon as omnilib/trailrunner#1 lands and is included in a release.

**Comment by jreese** [comment]
I started working on it last night, and I'll try to get it finished up and available tomorrow to test and validate.

**Comment by pmeier** [comment]
> I'm not personally fond of the idea of trying micromanage which files get formatting vs sorting vs both.

I thought a little more about this and, although it is sufficient for our use case, just wanted to give my two cents about this: As stated above there are files where sorting the imports is fine, but formatting the code is not. The reverse case is also common: in `__init__.py` files the order of the imports might be important to avoid cyclic imports, but the code can be formatted without issue. In this case we can get around that by using the `# usort:skip` directive, but IMO this already falls into the "micro-managing" category. 

So maybe give another thought to the idea of using the configuration files of both programs as source for what should happen to each file. Since you have control over `usort` it might be the easiest way to adopt `black`'s format to not need to recreate the logic for both individually.
