### ISSUE TITLE
pre-commit + excludes prevent people from committing code

### ISSUE THREAD

**Issue by cosinequanon** [omnilib/ufmt#148]
Currently the behavior of the CLI is to return an error code when no files can be formatted, e.g.
```
$ ufmt check foo.py
No files found
✨ 1 errors ✨
$ echo $?
1
```
This is probably okay for the interactive use case but this breaks how pre-commit works when used in conjunction with an exclusion rule in `pyproject.toml`. Say you have this set up
```
[tool.ufmt]
excludes = ["foo.py"]
```
Then if you do
```
$ echo "'a'" > foo.py
$ git add  foo.py
$ git commit -m 'test'
Format files with µfmt...................................................Failed
- hook id: ufmt
- exit code: 1

No files found
✨ 1 errors ✨
```
But this should absolutely not be an error! In fact it blocks people from committing things when they are totally valid.

I'm not sure what the best suggestion for a fix is, I'm happy to contribute it here if there is some agreement. Some ideas I had:
- Add a flag to the CLI to not have an error when this happens, e.g. `--ignore-no-files` or something
- Change the logic such that it's not an error to have no files in the CLI.
- Change the logic such that there is only an error if there are no files before the excludes
- Something else?

**Comment by cosinequanon** [comment]
FWIW `black` just exits with 0 in this case https://github.com/psf/black/blob/main/src/black/__init__.py#L710-L719

**Comment by amyreese** [comment]
I'll say the current behavior was originally intentional, but I agree that it's also not optimal. 😅

I think the best way to resolve this would be to move the `if empty` check from https://github.com/omnilib/ufmt/blob/main/ufmt/cli.py#L65 down into the section below, and add the "No files found" message to the list of reports. Maybe also change the emoji sparkles to something else in case of empty/error, so that it's more clear that it's not entirely successful, like `❗️` ?

Are you interested in submitting a PR for this?

**Comment by cosinequanon** [comment]
Okay cool, that approach works for me. I can submit a PR for this :)
