### ISSUE TITLE
ufmt runs slower than black+usort

### ISSUE THREAD

**Issue by Balandat** [omnilib/ufmt#4]
Running `ufmt` seems to be a bit slower than running `black` and `usort` successively:
```
(botorch) balandat@balandat-mbp botorch % time black --diff .
All done! ✨ 🍰 ✨
210 files would be left unchanged.
black --diff .  29.14s user 2.35s system 1021% cpu 3.082 total
(botorch) balandat@balandat-mbp botorch % time usort check .
Would sort botorch/acquisition/knowledge_gradient.py
usort check .  17.36s user 0.28s system 99% cpu 17.754 total
(botorch) balandat@balandat-mbp botorch % time ufmt check .
ufmt check .  32.73s user 0.39s system 99% cpu 33.294 total
```

This was on a vanilla clone of the botorch repo (`git clone https://github.com/pytorch/botorch`)

Not sure if this is expected.

**Comment by jreese** [comment]
So the obvious answer is that `black` runs as fast as it does because it uses a process pool to format multiple files at once. µfmt doesn't (yet) do this, but this shouldn't be too difficult to do with multiprocessing. We just need a better way to return results and output them in the parent process.
